TestWeb/Controllers/AdministracionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TestWeb.Controllers
{
    public class AdministracionController : Controller
    {
        // GET: Administracion
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Servicios()
        {
            return RedirectToAction("Index", "Servicios", null);
        }

        public ActionResult Razones()
        {
            return RedirectToAction("Index", "Razones", null);
        }

    }


}

TestWeb/Controllers/HomeController.cs
using Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using System.Data;
using System.Web.SessionState;

namespace TestWeb.Controllers
{
    public class HomeController : Controller
        
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }
    }

    
}

TestWeb/Controllers/UserController.cs
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using TestWeb.Models;
using Model;
using Microsoft.AspNet.Identity;
using System.Net.Mail;
using System.Web.UI.WebControls;
using System.Configuration;
using Model.Entities;

namespace TestWeb.Controllers
{
    public class UserController : Controller
    {
        private IncideEntities incideData = new IncideEntities();
        public UserController()
        {
        }


        private ApplicationRoleManager RoleManager
        {
            get
            {
                return HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
        }

        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        public async Task<ActionResult> Usuarios()
        {
            List<UsuarioIndexModel> usuarios = new List<UsuarioIndexModel>();
            foreach (var item in UserManager.Users.ToList())
            {
                var area = incideData.Area.Find(item.area).descripcion;
                var rol = await RoleManager.FindByIdAsync(item.Roles.ToList().FirstOrDefault().RoleId);
                usuarios.Add(new UsuarioIndexModel(item.Id, item.UserName, item.Email, item.exp, area, rol.Name, item.activo));

            }
            return View(usuarios);
        }

        [Authorize]
        public ActionResult Roles()
        {
            return View(RoleManager.Roles.ToList());
        }

        [HttpPost]
        [Authorize]
        public async Task<ActionResult> UsuarioRol(ChangeRolViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var user = await UserManager.FindByIdAsync(model.UserId);
            user.Roles.Clear();
            var result = await UserManager.AddToRoleAsync(model.UserId, model.Rol);
            if (!result.Succeeded)
            {
                AddErrors(result);
                ViewBag.UserId = new SelectList(UserManager.Users, "Id", "UserName", model.UserId);
                ViewBag.Rol = new SelectList(RoleManager.Roles, "Name", "Name", model.Rol);
                return View();
            }
            return RedirectToAction("UsuarioRol", new { message = ManageMessageId.ChangeRolSuccess});
        }

        [HttpGet]
        public ActionResult UsuarioRol (ManageMessageId? message)
        {
            ViewBag.UserId = new SelectList(UserManager.Users, "Id", "UserName"); 
            ViewBag.Rol = new SelectList(RoleManager.Roles, "Name", "Name");
            ViewBag.StatusMessage =
                message == ManageMessageId.Error ? "Se ha producido un error al cambiar el rol del usuario, por favor intentelo más tarde."
                : message == ManageMessageId.ErrorSameRol ? "El usuario ya se encuentra en el rol seleccionado, por favor seleccione otro."
                : message == ManageMessageId.ChangeRolSuccess ? "El rol del usuario se ha cambiado satisfactoriamente."
                : "";
            return View(); 
        }

        [Authorize]
        public async Task<ActionResult> Delete(string id)
        {
            var user = await UserManager.FindByIdAsync(id);
            user.activo = false;
            await UserManager.UpdateAsync(user);
            return RedirectToAction("Usuarios");
        }

        [Authorize]
        public async Task<ActionResult> Activate(string id)
        {
            var user = await UserManager.FindByIdAsync(id);
            user.activo = true;
            await UserManager.UpdateAsync(user);
            return RedirectToAction("Usuarios");
        }

        [HttpGet]
        [Authorize]
        public ActionResult AddRole()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public async Task<ActionResult> AddRole(AddRolViewModel model)
        {
            ApplicationRol rol = new ApplicationRol()
            {
                Name = model.Name
            };
            var result = await RoleManager.CreateAsync(rol);
            if (result.Succeeded)
            {
                var config = System.Web.Configuration.WebConfigurationManager.OpenWebConfiguration("~");
                KeyValueConfigurationElement keyValue = new KeyValueConfigurationElement(rol.Id, rol.Name);
                config.AppSettings.Settings.Add(keyValue);
                config.Save(ConfigurationSaveMode.Modified);
                return RedirectToAction("Roles");
            }
            AddErrors(result);
            return View(model);
            
        }

        [HttpGet]
        [Authorize]
        public ActionResult EditRole(string Id)
        {
            ApplicationRol rol = RoleManager.FindById(Id);
            EditRolViewModel model = new EditRolViewModel
            {
                Id = rol.Id,
                name = rol.Name
            };
            return View(model);

        }

        [HttpPost]
        [Authorize]
        public async Task<ActionResult> EditRole(EditRolViewModel model)
        {
            ApplicationRol rol = await RoleManager.FindByIdAsync(model.Id);
            rol.Name = model.name;
            var result = await RoleManager.UpdateAsync(rol);
            if (result.Succeeded)
            {
                var config = System.Web.Configuration.WebConfigurationManager.OpenWebConfiguration("~");
                config.AppSettings.Settings[rol.Id].Value = rol.Name;
                config.Save(ConfigurationSaveMode.Modified);
                return RedirectToAction("Roles");
            }
            AddErrors(result);
            return View(model);

        }

        [HttpGet]
        [Authorize]
        public ActionResult Edit (string id)
        {
            var user = UserManager.FindById(id);
            EditUserViewModel model = new EditUserViewModel()
            {
                UserName = user.UserName,
                id = user.Id,
                Email = user.Email,
                area = user.area,
                exp = user.exp,
                carneId = user.carneId
            };
            ViewBag.areas = incideData.Area.OrderBy(x => x.descripcion).ToList();
            return View(model);
        }

        [HttpPost]
        [Authorize(Roles = "Administrador")]
        public ActionResult Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    MailMessage email = new MailMessage();
                    SmtpClient client = new SmtpClient();
                    email.To.Add(model.Email);
                    email.Subject = "Notificación de Correo";
                    email.SubjectEncoding = System.Text.Encoding.UTF8;
                    email.Body = "Su correo es válido";
                    email.BodyEncoding = System.Text.Encoding.UTF8;
                    email.IsBodyHtml = false;
                    client.Send(email);
                }
                catch (Exception)
                {

                    ModelState.AddModelError("", "Introduzca un correo válido");
                    return View(model);
                }
                var user = UserManager.FindById(model.id);
                user.carneId = model.carneId;
                user.UserName = model.UserName;
                user.Email = model.Email;
                user.exp = model.exp;
                user.area = model.area;
                var result = UserManager.Update(user);
                if (result.Succeeded)
                {
                    return RedirectToAction("Usuarios");
                }
                AddErrors(result);
                
            }
            return View(model); 
        }

        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

        public enum ManageMessageId
        {
            Error,
            ErrorSameRol,
            ChangeRolSuccess
        }
    }
}

TestWeb/Views/Home/About.cshtml
@{
    ViewBag.Title = "Acerca de la Aplicación";
}
<h2>@ViewBag.Title.</h2>

<p>Aplicacion Web desarrollada por el Área de Informática del Centro de Inmuno Ensayo (CIE)</p>

TestWeb/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contacto";
}
<h2>@ViewBag.Title.</h2>

<address>
    134 esq. Avenida 25<br />
    La Habana, Cuba<br />
    <abbr title="Teléfono">T:</abbr>
    7-208 29 26 Ext 430
</address>

<address>
    <strong>Soporte:</strong>   
    <br />
    <a href="mailto:joan.oceguera@cie.cu">Joan Oceguera Nápoles</a>
    <br />
    <a href="mailto:ailin.valdes@cie.cu">Ailin Valdés Torres</a>
    <br />
    <a href="mailto:harol.picarin@cie.cu">Harol Picarín Pérez</a>
</address>

TestWeb/Views/Home/Index.cshtml
@using Model
@using System.Configuration
@{
    ViewBag.Title = "Servired 2.0";
}
<br />
@if (Request.IsAuthenticated)
{
    <div class="jumbotron">

        <h1>Bienvenido(a) </h1>
        <p class="lead">Gracias por visitarnos, @(CurrentUser.Get.FullName). Se encuentra logueado(a) como @CurrentUser.Get.Role </p>
    </div>
    <div class="row">
        @if (CurrentUser.Get.Role.Equals(ConfigurationManager.AppSettings.Get("11843472-ae59-423a-9ec4-6bca52a29b02")))
        {
            <div class="col">
                <div class="card">
                    <div class="card-header text-center font-weight-bold">
                        Solicitudes
                    </div>
                    <div class="card-body">
                        <p>Sección que permite visualizar las solicitudes realizadas y darle seguimiento a su estado</p>
                        <div class="container">
                            <div class="row justify-content-md-center">
                                <div class="col-auto">
                                    @Html.ActionLink("Solicitudes", "Index", "Solicitud", null, new { title = "Solicitudes", @class = "btn btn-primary btn-lg", @role = "button" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                    <div class="card">
                        <div class="card-header text-center font-weight-bold">
                            Usuarios
                        </div>
                        <div class="card-body">
                            <p>Sección que permite administrar los usuarios registrados en el sistema</p>
                            <div class="container">
                                <div class="row justify-content-md-center">
                                    <div class="col-auto">
                                        @Html.ActionLink("Usuarios", "Index", "User", null, new { title = "Usuarios", @class = "btn btn-primary btn-lg", @role = "button" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <div class="col">
                    <div class="card">
                        <div class="card-header text-center font-weight-bold">
                            Administración
                        </div>
                        <div class="card-body">
                            <p>Sección que permite administrar diversas funcionalidades del sistema</p>
                            <div class="container">
                                <div class="row justify-content-md-center">
                                    <div class="col-auto">
                                        @Html.ActionLink("Administración", "Index", "Administracion", null, new { title = "Administración", @class = "btn btn-primary btn-lg", @role = "button" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <div class="col">
                <div class="card">
                    <div class="card-header text-center font-weight-bold">
                        Reportes
                    </div>
                    <div class="card-body">
                        <p>Sección que permite visualizar reportes de la información almacenada en el sistema</p>
                        <div class="container">
                            <div class="row justify-content-md-center">
                                <div class="col-auto">
                                    @Html.ActionLink("Reportes", "Index", "Reportes", null, new { title = "Reportes", @class = "btn btn-primary btn-lg", @role = "button" })
                                </div>
                            </div>
                        </div>
                    </div>                        
                </div>
            </div>
        }
        else if (CurrentUser.Get.Role.Equals(ConfigurationManager.AppSettings.Get("d1bf455f-ee28-4e27-ab73-e98ba27269a2")))
        {
            <div class="col">
                <div class="card">
                    <div class="card-header text-center font-weight-bold">
                        Servicios
                    </div>
                    <div class="card-body">
                        <p>Sección que permite solicitar los servicios de red para un trabajador </p>
                        <div class="container">
                            <div class="row justify-content-md-center">
                                <div class="col-auto">
                                    @Html.ActionLink("Servicios", "Create", "Solicitud", null, new { @class = "btn btn-primary btn-lg", @role = "button" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <div class="card-header text-center font-weight-bold">
                        Solicitudes
                    </div>
                    <div class="card-body">
                        <p>Sección que permite visualizar las solicitudes realizadas y darle seguimiento a su estado</p>
                        <div class="container">
                            <div class="row justify-content-md-center">
                                <div class="col-auto">
                                    @Html.ActionLink("Solicitudes", "Index", "Solicitud", new { @area = CurrentUser.Get.area }, new { @class = "btn btn-primary btn-lg", @role = "button" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
        else if (CurrentUser.Get.Role.Equals(ConfigurationManager.AppSettings.Get("1462d873-de2b-4a77-8c7a-c6d84e581cd8")))
        {
            <div class="col">
                <div class="card">
                    <div class="card-header text-center font-weight-bold">
                        Servicios
                    </div>
                    <div class="card-body">
                        <p>Sección que permite solicitar los servicios de red para un trabajador </p>
                        <div class="container">
                            <div class="row justify-content-md-center">
                                <div class="col-auto">
                                    @Html.ActionLink("Servicios", "Create", "Solicitud", null, new {title = "Servicios", @class = "btn btn-primary btn-lg", @role = "button" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <div class="card-header text-center font-weight-bold">
                        Solicitudes
                    </div>
                    <div class="card-body">
                        <p>Sección que permite visualizar las solicitudes realizadas y darle seguimiento a su estado</p>
                        <div class="container">
                            <div class="row justify-content-md-center">
                                <div class="col-auto">
                                    @Html.ActionLink("Solicitudes", "Index", "Solicitud", new {title = "Solicitudes", @area = CurrentUser.Get.area }, new { @class = "btn btn-primary btn-lg", @role = "button" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                    <div class="card">
                        <div class="card-header text-center font-weight-bold">
                            Nuevo Usuario
                        </div>
                        <div class="card-body">
                            <p>Sección que permite añadir un nuevo usuario a la aplicación</p>
                            <div class="container">
                                <div class="row justify-content-md-center">
                                    <div class="col-auto">
                                        @Html.ActionLink("Nuevo Usuario", "Register", "Account", null, new { title = "Registrar Usuarios", @class = "btn btn-primary btn-lg", @role = "button" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
        }
        else
        {
            <div class="col">
                <div class="card">
                    <div class="card-header text-center font-weight-bold">
                        Solicitudes
                    </div>
                    <div class="card-body">
                        <p>Sección que permite visualizar las solicitudes realizadas y darle seguimiento a su estado</p>
                        <div class="container">
                            <div class="row justify-content-md-center">
                                <div class="col-auto">
                                    @Html.ActionLink("Solicitudes", "Index", "Solicitud", null, new { title = "Solicitudes", @class = "btn btn-primary btn-lg", @role = "button" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col">
                    <div class="card">
                        <div class="card-header text-center font-weight-bold">
                            Nuevo Usuario
                        </div>
                        <div class="card-body">
                            <p>Sección que permite añadir un nuevo usuario a la aplicación</p>
                            <div class="container">
                                <div class="row justify-content-md-center">
                                    <div class="col-auto">
                                        @Html.ActionLink("Nuevo Usuario", "Register", "Account", null, new { title = "Registrar Usuarios", @class = "btn btn-primary btn-lg", @role = "button" })
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            <div class="col">
                <div class="card">
                    <div class="card-header text-center font-weight-bold">
                        Reportes
                    </div>
                    <div class="card-body">
                        <p>Sección que permite visualizar reportes del sistema</p>
                        <div class="container">
                            <div class="row justify-content-md-center">
                                <div class="col-auto">
                                    @Html.ActionLink("Reportes", "Index", "Reportes", null, new { title = "Reportes", @class = "btn btn-primary btn-lg", @role = "button" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>                    
            </div>
        }
    </div>
}
else
{
    <div class="container-fluid">
        @Html.Partial("Login")
    </div>
}