TestWeb/Controllers/SolicitudController.cs
using Model.Entities;
using Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using DevExpress.XtraReports.UI;
using System.Text.RegularExpressions;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using TestWeb.Models;
using System.IO;
using System.Configuration;
using FunYCon;

namespace TestWeb.Controllers
{
    public class SolicitudController : Controller
    {
        private ServiciosEntities servData = new ServiciosEntities();
        private RecursosHumanosEntities rhData = new RecursosHumanosEntities();
        private IncideEntities incideData = new IncideEntities();
        private ApplicationRoleManager _roleManager
        {
            get
            {
                return HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
        }

        private ApplicationUserManager _userManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
        }

        [Authorize]
        public ActionResult Index(int area = 0)
        {
            
            var solicitudesModelView = new List<SolicitudIndexModel>();
            List<Solicitud> solicitudes = new List<Solicitud> ();
            if (area == 0)
                solicitudes = servData.Solicitud.OrderByDescending(x => x.fecha_solicitud).ToList();
            else
            {
                var personasArea = incideData.Persona.Where(x => x.id_area == area).ToList();
                var solicitudesOriginales = servData.Solicitud.OrderByDescending(x => x.fecha_solicitud).ToList();
                foreach (var solicitud in solicitudesOriginales)
                {
                    if (personasArea.Where(x => x.exp == solicitud.exp_benef && x.ci.Equals(solicitud.carneId)).Any())
                    {
                        solicitudes.Add(solicitud);
                    }
                }
            }

            foreach (var item in solicitudes)
            {
                var areaDescripcion = incideData.Area.First().descripcion;
                int jefe = (int)incideData.Area.First().Persona_jefe;
                int ExpJefe = incideData.Persona.Find(jefe).exp;
                string carnetJefe = incideData.Persona.Find(jefe).ci;

                var personaIncide = incideData.Persona.Where(x => x.ci == item.carneId && x.exp == item.exp_benef).SingleOrDefault();
                if (personaIncide != null)
                {
                    areaDescripcion = incideData.Area.Find(personaIncide.id_area).descripcion;
                    jefe = (int)incideData.Area.Find(personaIncide.id_area).Persona_jefe;
                    ExpJefe = incideData.Persona.Find(jefe).exp;
                    carnetJefe = incideData.Persona.Find(jefe).ci;
                }

                var validez = "";
                var solicitante = "";
                var beneficiado = "";
                if (item.exp_benef != null)
                {
                    var personaRHBeneficiado = rhData.Personal.Where(x => x.Exp == item.exp_benef && x.CarneId == item.carneId).ToList();
                    if (!personaRHBeneficiado.Any())
                    {
                        var personaBajasBeneficiado = rhData.BajasPers.ToList().Where(x => x.Exp == item.exp_benef && x.CarneId.Equals(item.carneId));
                        if (personaBajasBeneficiado.Any())
                        {
                            var persona = personaBajasBeneficiado.FirstOrDefault();
                            beneficiado = persona.Nombre + ' ' + persona.Apellido1 + ' ' + persona.Apellido2;
                        }

                    }
                    else
                    {
                        beneficiado = personaRHBeneficiado.First().Nombre + ' ' + personaRHBeneficiado.First().Apellido1 + ' ' + personaRHBeneficiado.First().Apellido2;
                    }
                }
               
                var personaRHSolicitante = rhData.Personal.Where(x => x.Exp == ExpJefe && x.CarneId.Equals(carnetJefe)).ToList();

                if (!personaRHSolicitante.Any())
                {
                    var personaBajasSolicitante = rhData.BajasPers.ToList().Where(x => x.Exp == ExpJefe && x.CarneId.Equals(carnetJefe)).FirstOrDefault();
                    solicitante = TConeccion.Revisar_Ort(personaBajasSolicitante.Nombre + ' ' + personaBajasSolicitante.Apellido1 + ' ' + personaBajasSolicitante.Apellido2);
                }
                else
                {
                    solicitante = TConeccion.Revisar_Ort(personaRHSolicitante.First().Nombre + ' ' + personaRHSolicitante.First().Apellido1 + ' ' + personaRHSolicitante.First().Apellido2);
                }
                solicitante = FunYCon.TConeccion.Revisar_Ort(solicitante);
                beneficiado = FunYCon.TConeccion.Revisar_Ort(beneficiado);
                if (item.validez != null)
                    validez = ((DateTime)item.validez).ToShortDateString();
                else
                    validez = "Mientras mantenga vinculo laboral";
                
                var estado = item.estado;
                var fechaSolicitud = item.fecha_solicitud;
                var tipoSolic = "";
                switch (item.tsolic)
                {
                    case ("c"):
                        tipoSolic = "Creación de usuario";
                        break;
                    case ("m"):
                        tipoSolic = "Modificación de usuario";
                        break;
                    case ("r"):
                        tipoSolic = "Renovacion de usuario";
                        break;


                }
                solicitudesModelView.Add(new SolicitudIndexModel(item.id, solicitante, beneficiado, validez, areaDescripcion, estado, ((DateTime)fechaSolicitud), tipoSolic));
            }
            return View(solicitudesModelView);
        }

        [Authorize]
        public ActionResult Details(int id)
        {
            return RedirectToAction("Planilla", new { id = id, detalle = true});
        }

        [Authorize]
        public ActionResult Create()
        {
            Solicitud solicitud = new Solicitud();
            Dictionary<string, string> personal = new Dictionary < string, string> ();
            Dictionary<string, string> rol = new Dictionary<string, string>();
            personal.Add("d","Dirigente");
            personal.Add("e", "Especialista");
            personal.Add("t", "Técnico");
            personal.Add("o", "Otros");
            rol.Add("u", "Usuario");
            rol.Add("ua", "Usuario Avanzado");
            rol.Add("a", "Administrador");
            ViewBag.Personal = new SelectList(personal, "Key", "Value");
            ViewBag.Rol = new SelectList(rol, "Key", "Value");
            ViewBag.Servicios = new SelectList(servData.Servicios.Where(x => x.activo).ToList(), "id", "nombre");
            ViewBag.area = new SelectList(incideData.Area.OrderBy(x=> x.descripcion).ToList(), "id_area", "descripcion");
            ViewBag.cuentasActivas = servData.Cuentas.Where(x => (bool)x.activo).ToList().Any();
            ViewBag.cuentasInactivas = servData.Cuentas.Where(x => !(bool)x.activo).ToList().Any();
            return View(solicitud);
        }

        [HttpPost]
        [Authorize]
        public ActionResult Create(FormCollection collection,  Solicitud model, int [] servicios)
        {

            var personaIncide = incideData.Persona.Where(x => x.exp == model.exp_benef && x.activo == 1).SingleOrDefault();
            int jefe = 0;
            int ExpJefe = 0;
            if (personaIncide != null)
            {
                jefe = (int)incideData.Area.Find(personaIncide.id_area).Persona_jefe;
                ExpJefe = incideData.Persona.Find(jefe).exp;
            }
            else
            {
                jefe = (int)incideData.Area.First().Persona_jefe;
                ExpJefe = incideData.Persona.Find(jefe).exp;
            }
            
            model.estado = "Solicitada";
            model.fecha_solicitud = DateTime.Now;
            model.usuario = CurrentUser.Get.UserId;
            model.carneId = rhData.Personal.Find(model.exp_benef).CarneId;
            if (servicios != null)
            {
                foreach (var item in servicios)
                {
                    Servicios servicio = servData.Servicios.Find(item);
                    model.Servicios.Add(servicio);
                }
            }
            if (model.tsolic.Equals("m"))
            {                    
                model.nombre_usuario = servData.Cuentas.Where(x => x.exp == model.exp_benef && (bool)x.activo).FirstOrDefault().nombre_usuario;
            }
            servData.Entry(model).State = EntityState.Added;
            servData.SaveChanges();
            return RedirectToAction("NotificarEsp", new { message = "Su solicitud se ha relizado correctamente y esta pendiente de aprobación", area = personaIncide.id_area, exp_benef = model.exp_benef, exp_solic = ExpJefe });
            
            
        }

        [HttpGet]
        [Authorize]
        public ActionResult Aprobar(int id)
        {
            var solicitud = servData.Solicitud.Find(id);
            solicitud.estado = "Aprobada";
            solicitud.fecha_aprobacion = DateTime.Now;
            servData.Entry(solicitud).State = EntityState.Modified;
            servData.SaveChanges();
            return RedirectToAction("NotificarAdm", new {  message = "La solicitud fue aprobada correctamente y está a la espera de ejecución", idSolicitud = id });
        }

        [HttpGet]
        public ActionResult Rechazar(int id)
        {
            ViewBag.id = id;
            ViewBag.razones = servData.Razones.Where(x => x.activo).ToList();
            return View();
        }

        [HttpPost]
        [Authorize]

TestWeb/Views/Solicitud/Index.cshtml
@using Model
@using System.Configuration
@model List<SolicitudIndexModel>

@{
    ViewBag.Title = "Solicitudes";
}

<h2>Solicitudes</h2>

<div>
    <a href="~/Solicitud/Create" title="Nueva Solicitud" class="btn btn-primary">
        <i class="glyphicon glyphicon-plus"></i>
    </a>
</div>
<br />
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.LabelFor(x => x.First().id)
            </th>
            <th>
                @Html.LabelFor(x => x.First().nombre_solic)
            </th>
            <th>
                @Html.LabelFor(x => x.First().nombre_benef)
            </th>
            <th>
                @Html.LabelFor(x => x.First().validez)
            </th>
            <th>
                @Html.LabelFor(x => x.First().tipoSolic)
            </th>
            <th>
                @Html.LabelFor(x => x.First().area)
            </th>
            <th>
                @Html.LabelFor(x => x.First().estado)
            </th>
            <th>
                @Html.LabelFor(x => x.First().fechaSolicitud)
            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.nombre_solic)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.nombre_benef)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.validez)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tipoSolic)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.area)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.estado)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fechaSolicitud)
                </td>
                <td class="col-2">
                @if (CurrentUser.Get.Role.Equals(ConfigurationManager.AppSettings.Get("11843472-ae59-423a-9ec4-6bca52a29b02")))
                {
                    <div class="form-group">
                        <div class="container-fluid">
                            <div class="form-row">
                                @if (Model.ToList().Where(x => x.id == item.id).Single().estado.Equals("Aprobada"))
                                {
                                    <div class="col-auto">
                                        <a href="~/Solicitud/Details/@item.id" title="Detalles" class="btn btn-info">
                                            <i class="glyphicon glyphicon-th-list"></i>
                                        </a>
                                    </div>
                                            <div class="col-auto">
                                                <a href="~/Solicitud/Planilla/@item.id" title="Crear Cuenta" class="btn btn-success">
                                                    <i class="glyphicon glyphicon-plus"></i>
                                                </a>
                                            </div>

                                }
                                else if (Model.ToList().Where(x => x.id == item.id).Single().estado.Equals("Ejecutada"))
                                {
                                    <div class="col-auto">
                                        <a href="~/Solicitud/Details/@item.id" title="Detalles" class="btn btn-info">
                                            <i class="glyphicon glyphicon-th-list"></i>
                                        </a>
                                    </div>
                                            <div class="col-auto">
                                                <a href="~/Solicitud/PrintViewToPdf/@item.id" title="Guardar Planilla" class="btn btn-primary">
                                                    <i class="glyphicon glyphicon-save"></i>
                                                </a>
                                            </div>

                                }
                                else
                                {
                                    <div class="col-auto">
                                        <a href="~/Solicitud/Details/@item.id" title="Detalles" class="btn btn-info">
                                            <i class="glyphicon glyphicon-th-list"></i>
                                        </a>
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                }
                else if (CurrentUser.Get.Role.Equals(ConfigurationManager.AppSettings.Get("8834006e-f16c-4f30-a924-ee00c2992b71")))
                {
                    <div class="form-group">
                        @if (Model.ToList().Where(x => x.id == item.id).Single().estado.Equals("Solicitada"))
                        {
                            <div class="container-fluid">
                                <div class="form-row">
                                    <div class="col-auto">
                                        <a href="~/Solicitud/Details/@item.id" title="Detalles" class="btn btn-info">
                                            <i class="glyphicon glyphicon-th-list"></i>
                                        </a>
                                    </div>
                                    <div class="col-auto">
                                        <a href="~/Solicitud/Aprobar/@item.id" title="Aprobar" class="btn btn-success">
                                            <i class="glyphicon glyphicon-ok"></i>
                                        </a>
                                    </div>
                                    <div class="col-auto">
                                        <a href="~/Solicitud/Rechazar/@item.id" title="Rechazar" class="btn btn-danger">
                                            <i class="glyphicon glyphicon-remove"></i>
                                        </a>
                                    </div>

                                </div>
                            </div>
                        }
                        else
                        {
                            <div class="col-auto">
                                <a href="~/Solicitud/Details/@item.id" title="Detalles" class="btn btn-info">
                                    <i class="glyphicon glyphicon-th-list"></i>
                                </a>
                            </div>
                        }
                    </div>
                }
                else
                {
                    <div class="col-auto">
                        <a href="~/Solicitud/Details/@item.id" title="Detalles" class="btn btn-info">
                            <i class="glyphicon glyphicon-th-list"></i>
                        </a>
                    </div>
                }
                </td>
            </tr>
        }
    </tbody>
</table>
<br />
<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <a href="~/Home/" title="Inicio" class="btn btn-secondary">
            <i class="glyphicon glyphicon-arrow-left"></i>
        </a>
    </div>
</div>

<script type="text/javascript">

    jQuery(function ($) {
        $('.table').DataTable({
            "order": [[7, "desc"]]
        });
    });

</script>

TestWeb/Views/Solicitud/NotificarAdm.cshtml
@{
    ViewBag.Title = "Notificar";
}

<h2>Notificar</h2>

<h3 class="text-success">@ViewBag.message </h3>

@using (Html.BeginForm("NotificarAdm", "Solicitud", FormMethod.Post, new { id = "form-solicitud", novalidate = true }))
{
    <input type="text" value="@ViewBag.solicitud" name="idSolicitud" hidden />
    <h4>Si desea notificar a los administradores, por favor selecciónelos</h4>
    <div class="card">
        <div class="card-header">
            Administradores
        </div>
        <div class="card-body">
            <ul class="list-group">
                @foreach (var item in ViewBag.datos)
                {
                    <li class="list-group-item">
                        <label><input type="checkbox" name="correos[]" value=@item.Email /> @item.FullName</label>
                    </li>
                }
            </ul>
        </div>
    </div>
    <br />
    <button type="submit" class="btn btn-primary">
        <span class="glyphicon glyphicon-send"></span>
    </button>
        <a href="~/Solicitud/" title="Solicitudes" class="btn btn-secondary">
            <i class="glyphicon glyphicon-arrow-left"></i>
        </a>
}

TestWeb/Views/Solicitud/NotificarEsp.cshtml
@{
    ViewBag.Title = "Notificar";
}

<h2>Notificar</h2>

<h3 class="text-success">@ViewBag.message </h3>

@using (Html.BeginForm("NotificarEsp", "Solicitud", FormMethod.Post, new { id = "form-solicitud", novalidate = true }))
{
    <input type="text" value="@ViewBag.area" name="area" hidden />
    <input type="text" value="@ViewBag.exp_benef" name="exp_benef" hidden />
    <input type="text" value="@ViewBag.exp_solic" name="exp_solic" hidden />
    <h4>Si desea notificar a los especialistas encargados, por favor selecciónelos</h4>
    <div class="card">
        <div class="card-header">
            Especialistas
        </div>
        <div class="card-body">
            <ul class="list-group">
                @foreach (var item in ViewBag.datos)
                {
                    <li class="list-group-item">
                        <label><input type="checkbox" name="correos[]" value=@item.Email /> @item.FullName</label>
                    </li>
                }
            </ul>
        </div>
    </div>
    <br />
    <button type="submit" class="btn btn-primary">
        <span class="glyphicon glyphicon-send"></span>
    </button>
        <a href="~/Solicitud/" title="Solicitudes" class="btn btn-secondary">
            <i class="glyphicon glyphicon-arrow-left"></i>
        </a>
}

TestWeb/Views/Solicitud/NotificarEspServ.cshtml
@{
    ViewBag.Title = "Notificar";
}

<h2>Notificar</h2>

<h3 class="text-success">@ViewBag.message </h3>

@using (Html.BeginForm("NotificarEspServ", "Solicitud", FormMethod.Post, new { id = "form-solicitud", novalidate = true }))
{
    <input type="text" value="@ViewBag.solicitud" name="idSolicitud" hidden />
    <input type="text" value="@ViewBag.direccion" name="direccion" hidden />
    <h4>Si desea notificar a los especialistas de servicios, por favor selecciónelos</h4>
    <div class="card">
        <div class="card-header">
            Especialistas de Servicios
        </div>
        <div class="card-body">
            <ul class="list-group">
                @foreach (var item in ViewBag.datos)
                {
                    <li class="list-group-item">
                        <label><input type="checkbox" name="correos[]" value=@item.Email /> @item.FullName</label>
                    </li>
                }
            </ul>
        </div>
    </div>
    <br />
    <button type="submit" class="btn btn-primary">
        <span class="glyphicon glyphicon-send"></span>
    </button>
    <a href="~/Solicitud/" title="Solicitudes" class="btn btn-secondary">
        <i class="glyphicon glyphicon-arrow-left"></i>
    </a>
}

TestWeb/Views/Solicitud/Rechazar.cshtml
@{
    ViewBag.Title = "Rechazar";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Rechazar", "Solicitud", FormMethod.Post, new { id = "form-solicitud", novalidate = true }))
{
    <div class="card">
        <div class="card-header">
            Razones para rechazar solicitud
        </div>
        <div class="card-body">
            <ul class="list-group">
                @foreach (var item in ViewBag.razones)
                {
                    <li class="list-group-item">
                        <label><input type="checkbox" name="razones[]" value=@item.id /> @item.descripcion</label>
                    </li>
                }
            </ul>
        </div>
    </div>
    <input type="text" hidden name="id" value="@ViewBag.id" />
    <br />
    <button type="submit" class="btn btn-primary">
        <span class="glyphicon glyphicon-send">
        </span>
    </button>
        <a href="~/Solicitud/" title="Solicitudes" class="btn btn-secondary">
            <i class="glyphicon glyphicon-arrow-left"></i>
        </a>
}