TestWeb/Controllers/CuentasController.cs
using Model.Entities;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace TestWeb.Controllers
{
    public class CuentasController : Controller
    {
        private ServiciosEntities db = new ServiciosEntities();

        // GET: Cuentas
        public ActionResult Index()
        {
            return View(db.Cuentas.ToList());
        }
        // GET: Cuentas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cuentas cuentas = db.Cuentas.Find(id);
            if (cuentas == null)
            {
                return HttpNotFound();
            }
            return View(cuentas);
        }

        // POST: Cuentas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cuentas cuentas = db.Cuentas.Find(id);
            cuentas.activo = false;
            db.Cuentas_Ausentes.RemoveRange(cuentas.Cuentas_Ausentes);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // POST: Cuentas/Delete/5
        [HttpGet, ActionName("Activar")]
        public ActionResult Activar(int id)
        {
            Cuentas cuentas = db.Cuentas.Find(id);
            cuentas.activo = true;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TestWeb/Controllers/ReportesController.cs
using Model.Entities;
using Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace TestWeb.Controllers
{
    public class ReportesController : Controller
    {
        private ServiciosEntities servData = new ServiciosEntities();
        private RecursosHumanosEntities rhData = new RecursosHumanosEntities();
        private IncideEntities incideData = new IncideEntities();

        // GET: Reportes
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        public ActionResult CuentasActivas(int [] servicios)
        {
            ViewBag.servicios = new SelectList(servData.Servicios.Where(x => x.activo).ToList(), "id", "nombre");
            var model = DataServicioActivo(servicios);
            return View(model);
        }

        [Authorize]
        public ActionResult Cuentas(int[] servicios)
        {
            ViewBag.servicios = new SelectList(servData.Servicios.Where(x => x.activo).ToList(), "id", "nombre");
            var model = DataServicio(servicios);
            return View(model);
        }

        [Authorize]
        public List<ReporteServicioModel> DataServicioActivo(int [] servicios)
        {
            List<Cuentas> cuentas = servData.Cuentas.Where(x => (bool) x.activo).ToList();
            List<ReporteServicioModel> data = new List<ReporteServicioModel>();
            if (servicios != null)
            {
                foreach (var item in servicios)
                {
                    Servicios servicio = servData.Servicios.Find(item);
                    cuentas = cuentas.Where(x => x.Servicios.Contains(servicio)).ToList();
                }
            }
            foreach (var item in cuentas)
            {
                string nombre = "";
                string area = "";
                if (item.exp != null)
                {
                    if (rhData.Personal.Where(x => x.Exp == item.exp && x.CarneId.Equals(item.carneId)).Any())
                    {
                        var personaRh = rhData.Personal.Find(item.exp);
                        nombre = FunYCon.TConeccion.Revisar_Ort(personaRh.Nombre + " " + personaRh.Apellido1 + " " + personaRh.Apellido2);
                    }
                    else
                    {
                        var personaRh = rhData.BajasPers.Where(x => x.Exp == item.exp && x.CarneId.Equals(item.carneId)).FirstOrDefault();
                        nombre = FunYCon.TConeccion.Revisar_Ort(personaRh.Nombre + " " + personaRh.Apellido1 + " " + personaRh.Apellido2);
                    }

                    var persona  = incideData.Persona.Where(x => x.exp == item.exp).ToList();
                    if (persona != null)
                    {
                        int idArea = (int) persona.First().id_area;
                        if (incideData.Area.Find(idArea) != null)
                        {
                            area = incideData.Area.Find(idArea).descripcion;
                        }
                    }
                }
                data.Add(new ReporteServicioModel {

                    exp = item.exp,
                    nombre = nombre,
                    nombre_usuario = item.nombre_usuario,
                    area = area
                }); 
            }
            return data;
        }

        [Authorize]
        public List<ReporteServicioModel> DataServicio(int [] servicios)
        {
            List<Cuentas> cuentas = servData.Cuentas.ToList();
            List<ReporteServicioModel> data = new List<ReporteServicioModel>();
            if (servicios != null)
            {
                foreach (var item in servicios)
                {
                    Servicios servicio = servData.Servicios.Find(item);
                    cuentas = cuentas.Where(x => x.Servicios.Contains(servicio)).ToList();
                }
            }
            foreach (var item in cuentas)
            {
                string nombre = "";
                string area = "";
                if (item.exp != null)
                {
                    if (rhData.Personal.Where(x => x.Exp == item.exp && x.CarneId.Equals(item.carneId)).Any())
                    {
                        var personaRh = rhData.Personal.Find(item.exp);
                        nombre = FunYCon.TConeccion.Revisar_Ort(personaRh.Nombre + " " + personaRh.Apellido1 + " " + personaRh.Apellido2);
                    }
                    else
                    {
                        var personaRh = rhData.BajasPers.Where(x => x.Exp == item.exp && x.CarneId.Equals(item.carneId)).FirstOrDefault();
                        nombre = FunYCon.TConeccion.Revisar_Ort(personaRh.Nombre + " " + personaRh.Apellido1 + " " + personaRh.Apellido2);
                    }

                    int idArea = (int)incideData.Persona.Where(x => x.exp == item.exp).FirstOrDefault().id_area;
                    area = incideData.Area.Find(idArea).descripcion;
                }
                data.Add(new ReporteServicioModel
                {

                    exp = item.exp,
                    nombre = nombre,
                    nombre_usuario = item.nombre_usuario,
                    area = area
                });
            }
            return data;
        }
    }
}

TestWeb/Views/Reportes/Cuentas.cshtml
@model IEnumerable<Model.ReporteServicioModel>

@{
    ViewBag.Title = "Cuentas ";
}

<h2>Servicios</h2>
<br />
@using (Html.BeginForm("Cuentas", "Reportes", FormMethod.Get, new { id = "form-solicitud" }))

{
    <div>
        @Html.DropDownList("servicios", null, htmlAttributes: new { @class = "form-control Select2", id = "selectServicios", name = "servicios", style = "width:250px;", @multiple = true })
    </div>
    <br />
    <button type="submit" class="btn btn-primary" title="Solicitar">
        <span class="glyphicon glyphicon-send"></span>
    </button>
}

<br />
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.exp)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nombre_usuario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.area)
            </th>
        </tr>
    </thead>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.exp)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nombre_usuario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.area)
            </td>
        </tr>
    }
</table>
<br />
<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <a href="~/Reportes/Index" title="Reportes" class="btn btn-secondary">
            <i class="glyphicon glyphicon-arrow-left"></i>
        </a>
    </div>
</div>
<script type="text/javascript">
         $(document).ready(function ()
    {
                    jQuery(function ($) {
                        $('.table').DataTable();
                    });

           $('.Select2').select2({
               placeholder: "Seleccione los servicios"
           });
    });
</script>

TestWeb/Views/Reportes/CuentasActivas.cshtml
@model IEnumerable<Model.ReporteServicioModel>

@{
    ViewBag.Title = "Cuentas Activas";
}

<h2>Servicios</h2>
<br />
@using (Html.BeginForm("CuentasActivas", "Reportes", FormMethod.Get, new { id = "form-solicitud" }))

{
    <div>
        @Html.DropDownList("servicios", null, htmlAttributes: new { @class = "form-control Select2", id = "selectServicios", name = "servicios", style = "width:250px;", @multiple = true})
    </div>
     <br />
    <button type="submit" class="btn btn-primary" title="Solicitar">
        <span class="glyphicon glyphicon-send"></span>
    </button>
}
    
<br />
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.exp)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nombre_usuario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.area)
            </th>
        </tr>
    </thead>
    
@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.exp)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nombre_usuario)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.area)
        </td>
    </tr>
}
</table>
<br />
<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <a href="~/Reportes/Index" title="Reportes" class="btn btn-secondary">
            <i class="glyphicon glyphicon-arrow-left"></i>
        </a>
    </div>
</div>
<script type="text/javascript">
         $(document).ready(function ()
    {
                    jQuery(function ($) {
                        $('.table').DataTable();
                    });

           $('.Select2').select2({
               placeholder: "Seleccione los servicios"
           });
    });
</script>

TestWeb/Views/Reportes/Index.cshtml
@{
    ViewBag.Title = "Reportes";
}
<br />
<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-header text-center font-weight-bold">
                Cuentas Activas
            </div>
            <div class="card-body">
                <p>Sección que permite consultar las cuentas activas en el sistema y filtrarlas por servicios</p>
                <div class="container">
                    <div class="row justify-content-md-center">
                        <div class="col-auto">
                            @Html.ActionLink("Cuentas Activas", "CuentasActivas", "Reportes", null, new { @class = "btn btn-primary btn-lg", @role = "button" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card">
            <div class="card-header font-weight-bold text-center">
                Cuentas
            </div>
            <div class="card-body">
                <p>Sección que permite consultar todas las cuentas en el sistema y filtrarlas por servicios</p>
                <div class="container">
                    <div class="row justify-content-md-center">
                        <div class="col-auto">
                            @Html.ActionLink("Cuentas ", "Cuentas", "Reportes", null, new { @class = "btn btn-primary btn-lg", @role = "button" })
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<br />
<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <a href="~/Home/" title="Inicio" class="btn btn-secondary">
            <i class="glyphicon glyphicon-arrow-left"></i>
        </a>
    </div>
</div>